#!/usr/bin/env python3
"""
ML QC Agent
===========
Reads an ml_qc_metrics.json file and produces a pre-training quality-control
report with per-check 🟢/🟡/🔴 flags and actionable recommendations.

The agent is a constrained specialist: it interprets the provided metrics
using standard ML knowledge but never invents numbers not in the JSON.

Usage:
    python agents/ml_qc_agent.py [path-to-ml_qc_metrics.json]
"""

import json
import sys
from pathlib import Path
from dotenv import load_dotenv
from anthropic import Anthropic

load_dotenv(Path(__file__).parent.parent / ".env")
client = Anthropic()

DEFAULT_METRICS = (Path(__file__).parent.parent / "projects" /
                   "02-breast-cancer-ml" / "data" / "ml_qc_metrics.json")

SYSTEM_PROMPT = """You are a machine learning quality-control reviewer. Your job is to
inspect pre-training QC metrics for a classification dataset and flag problems
BEFORE a model is trained.

STRICT RULES:
- Use only the metrics provided in the JSON — never invent numbers
- Assign each check a flag: 🟢 (fine), 🟡 (caution), 🔴 (serious problem)
- Be specific and quantitative: cite the actual values from the JSON
- Give concrete, actionable recommendations (e.g. "apply SMOTE or class weights"
  for imbalance, "use StandardScaler" for scale disparity)
- Do not overstate: a 1.7:1 imbalance is mild, not a crisis
- Data leakage is the most serious flag — if suspicious features exist, treat as 🔴
- Write in clear prose, professional but direct

FLAGGING GUIDANCE:
- Class imbalance: 🟢 up to ~1.5:1, 🟡 ~1.5-3:1, 🔴 above ~3:1
- Missing values: 🟢 none, 🟡 under 5%, 🔴 above 5%
- Scale disparity: 🟢 ratio under ~100, 🟡 100-1000, 🔴 above 1000 (always rec. scaling)
- Constant features: 🟢 none, 🟡/🔴 if any (should be dropped)
- Correlated pairs: 🟢 none, 🟡 a few, 🔴 many (note redundancy)
- Outliers: contextual — note prevalence, recommend inspection if high
- Leakage risk: 🟢 none, 🔴 if any suspicious feature exists

OUTPUT FORMAT — write exactly these sections:
## Overall Assessment
[2-3 sentences: is this dataset ready for training? Biggest concern?]

## Check-by-Check Findings
[One short paragraph per check, each starting with its flag emoji and check name]

## Recommendations
[Numbered, prioritized, concrete actions before training]"""


def load_metrics(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"QC metrics not found at: {path}")
    with open(path) as f:
        return json.load(f)


def generate_report(metrics: dict) -> tuple[str, int, int]:
    user_message = f"""Review the pre-training QC metrics for this classification dataset
and produce the QC report.

ML QC METRICS:
{json.dumps(metrics, indent=2)}

Assign flags, cite the actual numbers, and give prioritized recommendations."""

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1800,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_message}]
    )
    return (response.content[0].text,
            response.usage.input_tokens,
            response.usage.output_tokens)


def main():
    if len(sys.argv) > 1:
        metrics_path = Path(sys.argv[1]).resolve()
    else:
        metrics_path = DEFAULT_METRICS

    print("=" * 40)
    print("  ML QC Agent")
    print("=" * 40)

    print(f"\n[1/3] Loading: {metrics_path}")
    try:
        metrics = load_metrics(metrics_path)
    except FileNotFoundError as e:
        print(f"\nERROR: {e}")
        print("Run 00_ml_qc_metrics.py first to generate the metrics.")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"\nERROR: Invalid JSON: {e}")
        sys.exit(1)

    cb = metrics.get("class_balance", {})
    print(f"  Samples:          {cb.get('n_samples', '?')}")
    print(f"  Imbalance ratio:  {cb.get('imbalance_ratio', '?')}")

    print(f"\n[2/3] Calling Claude API...")
    try:
        report, t_in, t_out = generate_report(metrics)
    except Exception as e:
        print(f"\nERROR: API call failed: {e}")
        sys.exit(1)

    cost = (t_in * 3 + t_out * 15) / 1_000_000
    print(f"  Tokens: {t_in} in / {t_out} out")
    print(f"  Cost:   ${cost:.4f}")

    output_path = metrics_path.parent.parent / "report" / "ml_qc_report.md"
    print(f"\n[3/3] Saving to: {output_path}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("# ML Dataset QC Report\n\n")
        f.write("*Pre-training quality control — generated by ML QC Agent*\n\n")
        f.write("---\n\n")
        f.write(report)

    print(f"\n{'=' * 40}")
    print(f"  DONE  |  Output: {output_path}")
    print(f"{'=' * 40}")


if __name__ == "__main__":
    main()
